# Generated by Django 6.0.3 on 2026-03-25 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0007_alter_fotografia_publicada'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='urlapi',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
