# Generated by Django 6.0.3 on 2026-03-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0009_alter_fotografia_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='urlapi',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
