# Generated by Django 6.0.3 on 2026-03-26 13:31

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0010_alter_fotografia_urlapi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fotografia',
            name='foto',
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='urlapi',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='foto'),
        ),
    ]
