# Generated by Django 6.0.3 on 2026-03-26 13:38

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0011_remove_fotografia_foto_alter_fotografia_urlapi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='urlapi',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='urlapi'),
        ),
    ]
