# Generated by Django 6.0.3 on 2026-03-26 13:44

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0012_alter_fotografia_urlapi'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='foto',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='foto'),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='urlapi',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
